### ISSUE TITLE
Support for Activity Result API?

### ISSUE THREAD

**Issue by langsmith** [persona-id/persona-android-sdk#3]
Hey, great SDK that you all have going. I'm reaching out to see whether you all have plans to support the Activity Result API https://developer.android.com/training/basics/intents/result#register .  I see `onActivityResult()` usage in the docs and at https://github.com/persona-id/persona-android-sdk/blob/main/app/src/main/java/com/withpersona/sdk/demo/MainActivity.kt#L75, but was hoping maybe you all are looking into providing more flexibility for this use case.

Getting deprecation notices in Android Studio around `onActivityResult()` usage

<img width="627" alt="Screen Shot 2021-02-03 at 8 59 51 PM" src="https://user-images.githubusercontent.com/4394910/106846983-df0e0c00-6662-11eb-8c0d-66db16a2e7b7.png">

<img width="723" alt="Screen Shot 2021-02-03 at 8 59 57 PM" src="https://user-images.githubusercontent.com/4394910/106846981-dc131b80-6662-11eb-9554-960afb8d39df.png">

**Comment by SalvatoreT** [comment]
Yes! The Activity Result API is great, and we'll add official support when the stable release of `androidx.activity:activity:1.2.0` is out.

**Comment by langsmith** [comment]
Great. Thanks for the update,  @SalvatoreT .
