### ISSUE TITLE
Resuming an Inquiry from ID and Session Token is not working.

### ISSUE THREAD

**Issue by shirsh94** [persona-id/persona-android-sdk#72]
Example from Documentation.

**Starting/Resuming an Inquiry from ID**
When you create an Inquiry on the server, you can pass the Inquiry ID instead of the Template ID.

val inquiry = Inquiry.fromInquiry("inq_123456")
  .build()
If the Inquiry has already started, you will need to also pass in the session token.

val inquiry = Inquiry.fromInquiry("inq_123456")
  .sessionToken("ABD1234567890")
  .build()

https://docs.withpersona.com/docs/android-sdk-v2-integration-guide#startingresuming-an-inquiry-from-id

**Comment by persona-identities** [comment]
Hi shirsh94. Does the inquiry you are trying to resume have PII on it (i.e. a picture of an id has been uploaded, a selife has been taken, etc)? If so, you can't reuse the session token while resuming it and will need to get a new one. See: https://docs.withpersona.com/docs/security#resuming-pending-inquiries

This link has instructions on how to get a new session token: https://docs.withpersona.com/docs/inquiries-resuming-inquiries
