### ISSUE TITLE
Android theme variables documentation

### ISSUE THREAD

**Issue by kattatzu** [persona-id/persona-android-sdk#88]
Please document the supported variables to customize the native integration in Android, since it does not accept the variables mentioned in the v1 documentation nor those of React.

Greetings

**Comment by jacoblange-dev** [comment]
We will be marking our client side theming support as deprecated in an upcoming release. The release will go live sometime this week or next, at which point you will be able to set "server" as the theme source and configure your theme in the Persona Dashboard. I'm going to close this but will update this thread when that release goes live.

You can still view the client side theming attributes on Android by browsing the xml files of our `inquiry-resources` package via Android Studio.

**Comment by kattatzu** [comment]
Thank you for the info 
@jacoblange-dev

**Comment by daniel-e-gonzalez** [comment]
Following up here, we released the new react native sdk that can use "server" as the theme source today in version 2.4.0. Here's some links that should be helpful:

https://docs.withpersona.com/docs/react-native-sdk-integration#theming <- basic info for theming on the react native sdk.
https://support.withpersona.com/hc/en-us/articles/13775762246547-Tutorial-Configure-a-Theme-with-Inquiry-Template-Editor <- instructions on theming in the dashboard.
https://docs.withpersona.com/docs/react-native-sdk-v2-changelogs#changed <- changelog with some more info about the deprecation.
